from tkinter import *
from PIL import Image, ImageTk


root = Tk()
root.geometry("665x400")
root.resizable(width=False, height=False)
menubar = Menu(root)
Kezdőoldalmenu = Menu(menubar, tearoff=0)
menubar.add_cascade(label="Kezdőoldal")
menubar.add_cascade(label="Akasztófa")
menubar.add_cascade(label="Valuta Váltó")
menubar.add_cascade(label="Valorant Line-up Guide")
menubar.add_cascade(label="QR kód generátor")
menubar.add_cascade(label="Jelszó generátor")
menubar.add_cascade(label="Naptár")
aksztofa=menubar.add_cascade(label="Iraki óra")
akszto=Menu(menubar, tearoff=0)
valuta=Menu(menubar, tearoff=0)
valolineup=Menu(menubar, tearoff=0)
qrkodgen=Menu(menubar, tearoff=0)
jelszogen=Menu(menubar, tearoff=0)
naptar=Menu(menubar, tearoff=0)
irakiora=Menu(menubar, tearoff=0)
elsomondat=Label(root, text="Üdvözlünk az alkalmazásunkban ami tele van minden-féle jósággal!", font=("Arial", 14,""))
masodikmondat=Label(root, text="Akasztófa, Valuta váltó, Valorant Line-up Guide, QR kód generátor,\n Jelszó generátor, Naptár és egy kis meglepetés", font=("Arial", 12,""))
harmadikmondat=Label(root, text="Válassz a menüpontok között és kezdd meg a világmegváltást még ma!", font=("Arial", 12,""))
elsomondat.pack()
masodikmondat.place(x=95, y=124)
harmadikmondat.place(x=80, y=214)
logo=Image.open("Névtelen.png")
test = ImageTk.PhotoImage(logo)
label1 = Label(image=test)
label1.place(x=262, y=250)
root.config(menu=menubar)
root.mainloop()