from tkinter import *
from PIL import ImageTk, Image  


root = Tk()
root.geometry("680x400")
menubar = Menu(root)
Kezdőoldalmenu = Menu(menubar, tearoff=0)
menubar.add_cascade(label="Kezdőooldal")
menubar.add_cascade(label="Akasztófa")
menubar.add_cascade(label="Valuta Váltó")
menubar.add_cascade(label="Valorant Line-up Guide")
menubar.add_cascade(label="QR kód generátor")
menubar.add_cascade(label="Jelszó generátor")
menubar.add_cascade(label="Naptár")
aksztofa=menubar.add_cascade(label="Iraki óra")
akszto=Menu(menubar, tearoff=0)
valuta=Menu(menubar, tearoff=0)
valolineup=Menu(menubar, tearoff=0)
qrkodgen=Menu(menubar, tearoff=0)
jelszogen=Menu(menubar, tearoff=0)
naptar=Menu(menubar, tearoff=0)
irakiora=Menu(menubar, tearoff=0)
elsomondat=Label(root, text="Üdvözlünk az alkalmazásunkban ami tele van minden-féle jósággal!")
masodikmondat=Label(root, text="Akasztófa, Valuta váltó, Valorant Line-up Guide, QR kód generátor, Jelszó generátor, Naptár és egy kis meglepetés")
harmadikmondat=Label(root, text="Válassz a menüpontok között és kezdd meg a világmegváltást még ma!")
logo=Image.open("")
root.config(menu=menubar)
root.mainloop()